kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cert-manager-istio-csr.name" . }}-dynamic-istiod
  namespace: {{ .Values.app.istio.namespace }}
  labels:
    {{- include "cert-manager-istio-csr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-istio-csr.name" . }}-dynamic-istiod
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-istio-csr.name" . }}
  namespace: {{ .Release.Namespace }}

